version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: mi_base_datos
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contrasena
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flask_app:
    build: ./app
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - APP_NAME=Flask de Producción
      - APP_VERSION=1.0.0
      - DB_HOST=db
      - DB_NAME=mi_base_datos
      - DB_USER=usuario
      - DB_PASSWORD=contrasena
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: